import { resolve, dirname, join, relative, basename } from 'node:path';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { loadConfig } from './config.js';
import { readManifest, hashContent, type Manifest } from './manifest.js';
import { resolveLlmConfig, chatCompletion } from './llm.js';
import { EnrichError } from '../errors.js';
import type { FixedCodeConfig } from '../types.js';

export interface EnrichOptions {
  outputDir: string;
  specFile?: string;
  file?: string;
  force?: boolean;
  configPath?: string;
  llmOverrides?: { provider?: string; model?: string };
}

export interface EnrichResult {
  enriched: string[];
  skipped: string[];
  errors: string[];
}

interface PromptParts {
  system: string;
  user: string;
}

interface NeighbourFile {
  path: string;
  content: string;
}

/**
 * Extract code from LLM response, stripping markdown fences if present.
 */
export function extractCode(raw: string): string {
  const trimmed = raw.trim();
  const fenceMatch = trimmed.match(/^```(?:\w+)?\s*\n([\s\S]*?)\n?```\s*$/);
  if (fenceMatch) {
    return fenceMatch[1];
  }
  return trimmed;
}

/**
 * Split a PascalCase/camelCase identifier into tokens.
 */
function splitTokens(name: string): string[] {
  return name.split(/(?=[A-Z])/).filter(Boolean);
}

/**
 * Check if two names share at least one significant token (length >= 4).
 */
function hasSharedToken(a: string, b: string): boolean {
  const tokensA = splitTokens(a);
  const tokensB = new Set(splitTokens(b));
  return tokensA.some(t => t.length >= 4 && tokensB.has(t));
}

/**
 * Find neighbouring generated files relevant to an extension point.
 * Prioritises: same directory > parent directory > name affinity.
 * Only includes overwrite:true files (generated, not other extension points).
 */
export function findNeighbours(
  extensionPointPath: string,
  manifest: Manifest,
  maxFiles: number = 10
): string[] {
  const dir = dirname(extensionPointPath);
  const parentDir = dirname(dir);
  const baseName = basename(extensionPointPath).replace(/^Default/, '').replace(/\.\w+$/, '');

  const candidates: Array<{ path: string; score: number }> = [];

  for (const [filePath, entry] of Object.entries(manifest.files)) {
    // Skip extension points and the file itself
    if (!entry.overwrite || filePath === extensionPointPath) continue;

    const fileDir = dirname(filePath);

    if (fileDir === dir) {
      // Same directory — highest relevance
      candidates.push({ path: filePath, score: 3 });
    } else if (fileDir === parentDir || dirname(fileDir) === parentDir) {
      // Parent directory or sibling directory — check name affinity
      const fileBase = basename(filePath).replace(/\.\w+$/, '');
      if (fileBase.includes(baseName) || baseName.includes(fileBase) || hasSharedToken(baseName, fileBase)) {
        candidates.push({ path: filePath, score: 2 });
      }
    }
    // Files further away are not included
  }

  // Sort by score (descending), then alphabetically for stability
  candidates.sort((a, b) => b.score - a.score || a.path.localeCompare(b.path));

  return candidates.slice(0, maxFiles).map(c => c.path);
}

/**
 * Build the prompt for enriching an extension point.
 */
export function buildEnrichPrompt(input: {
  specYaml: string;
  stubPath: string;
  stubContent: string;
  neighbours: NeighbourFile[];
}): PromptParts {
  const system = `You are implementing business logic for a generated extension point file.

The file was generated by FixedCode as a stub with TODOs. Your job is to implement the business logic based on the original spec and the related generated files.

Rules:
- Implement all TODO stubs with working business logic based on the spec and related files.
- Preserve all existing signatures, class names, and imports.
- Follow the patterns established in the related files.
- Do not add features beyond what the spec describes.
- Output ONLY the complete file. No explanation, no markdown fences, no commentary.`;

  let user = `## Original Spec\n\n\`\`\`yaml\n${input.specYaml}\n\`\`\`\n\n`;
  user += `## Extension Point (file to implement)\n\nPath: ${input.stubPath}\n\n\`\`\`\n${input.stubContent}\n\`\`\`\n`;

  if (input.neighbours.length > 0) {
    user += '\n## Related Generated Files\n';
    for (const n of input.neighbours) {
      user += `\nPath: ${n.path}\n\n\`\`\`\n${n.content}\n\`\`\`\n`;
    }
  }

  return { system, user };
}

/**
 * Check if extension point files have been modified since generation.
 * Compares current file content hash against the manifest hash.
 * If they match, the file is still the original stub — safe to overwrite.
 * If they differ, the user has edited it — refuse unless --force.
 */
function checkModified(outputDir: string, files: string[], manifest: Manifest): string[] {
  const modified: string[] = [];
  for (const file of files) {
    const absPath = resolve(outputDir, file);
    if (!existsSync(absPath)) continue;

    const entry = manifest.files[file];
    if (!entry) continue;

    const currentHash = hashContent(readFileSync(absPath, 'utf-8'));
    if (currentHash !== entry.hash) {
      modified.push(file);
    }
  }
  return modified;
}

/**
 * Enrich extension point files with AI-generated business logic.
 */
export async function enrich(options: EnrichOptions): Promise<EnrichResult> {
  const outputDir = resolve(options.outputDir);
  const config = loadConfig(process.cwd(), options.configPath);
  const llmConfig = resolveLlmConfig(config, options.llmOverrides);

  // Read manifest
  const manifest = readManifest(outputDir);
  if (!manifest) {
    throw new EnrichError(`No .fixedcode-manifest.json found in ${outputDir}`);
  }

  // Find extension points (overwrite: false)
  let extensionPoints = Object.entries(manifest.files)
    .filter(([, entry]) => !entry.overwrite)
    .map(([path, entry]) => ({ path, entry }));

  if (extensionPoints.length === 0) {
    console.log('No extension points found.');
    return { enriched: [], skipped: [], errors: [] };
  }

  // Filter to specific file if --file provided
  if (options.file) {
    extensionPoints = extensionPoints.filter(ep => ep.path === options.file);
    if (extensionPoints.length === 0) {
      throw new EnrichError(`File '${options.file}' is not an extension point in the manifest`);
    }
  }

  // Safety check: refuse to overwrite user-modified extension points
  if (!options.force) {
    const modified = checkModified(outputDir, extensionPoints.map(ep => ep.path), manifest);
    if (modified.length > 0) {
      throw new EnrichError(
        `Extension point files have been modified since generation. Use --force to overwrite.\nModified files:\n  ${modified.join('\n  ')}`
      );
    }
  }

  const result: EnrichResult = { enriched: [], skipped: [], errors: [] };

  // Create backup directory for original stubs
  const backupDir = join(outputDir, '.fixedcode-enrich-backup');
  mkdirSync(backupDir, { recursive: true });

  // Group by specFile for efficient spec loading
  const bySpec = new Map<string, typeof extensionPoints>();
  for (const ep of extensionPoints) {
    const specKey = options.specFile ?? ep.entry.specFile ?? '__unknown__';
    if (!bySpec.has(specKey)) bySpec.set(specKey, []);
    bySpec.get(specKey)!.push(ep);
  }

  for (const [specKey, eps] of bySpec) {
    // Load spec YAML
    let specYaml: string;
    if (specKey === '__unknown__') {
      if (options.specFile) {
        specYaml = readFileSync(resolve(options.specFile), 'utf-8');
      } else {
        console.warn('Warning: no specFile recorded in manifest. Use --spec to provide one.');
        for (const ep of eps) result.skipped.push(ep.path);
        continue;
      }
    } else {
      const specPath = options.specFile
        ? resolve(options.specFile)
        : resolve(outputDir, specKey);
      if (!existsSync(specPath)) {
        console.warn(`Warning: spec file not found: ${specPath}`);
        for (const ep of eps) result.skipped.push(ep.path);
        continue;
      }
      specYaml = readFileSync(specPath, 'utf-8');
    }

    // Process each extension point sequentially
    for (const ep of eps) {
      const absPath = resolve(outputDir, ep.path);
      if (!existsSync(absPath)) {
        result.skipped.push(ep.path);
        continue;
      }

      try {
        const stubContent = readFileSync(absPath, 'utf-8');

        // Gather neighbours
        const neighbourPaths = findNeighbours(ep.path, manifest);
        const neighbours: NeighbourFile[] = neighbourPaths
          .map(p => {
            const nPath = resolve(outputDir, p);
            if (!existsSync(nPath)) return null;
            return { path: p, content: readFileSync(nPath, 'utf-8') };
          })
          .filter((n): n is NeighbourFile => n !== null);

        // Build prompt
        const prompt = buildEnrichPrompt({
          specYaml,
          stubPath: ep.path,
          stubContent,
          neighbours,
        });

        // Call LLM
        const response = await chatCompletion(llmConfig, [
          { role: 'system', content: prompt.system },
          { role: 'user', content: prompt.user },
        ], { maxTokens: 8192 });

        const code = extractCode(response);

        // Backup original stub
        const backupPath = join(backupDir, ep.path);
        mkdirSync(dirname(backupPath), { recursive: true });
        writeFileSync(backupPath, stubContent, 'utf-8');

        // Write enriched version in place
        writeFileSync(absPath, code, 'utf-8');
        result.enriched.push(ep.path);
        console.log(`  Enriched: ${ep.path}`);
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unknown error';
        result.errors.push(ep.path);
        console.error(`  Error enriching ${ep.path}: ${message}`);
      }
    }
  }

  if (result.enriched.length > 0) {
    console.log(`\nEnriched ${result.enriched.length} extension point(s).\n`);

    // Show diffs
    for (const ep of result.enriched) {
      const backupPath = join(backupDir, ep);
      const enrichedPath = resolve(outputDir, ep);
      console.log(`--- ${ep} ---`);
      try {
        const diff = execFileSync('diff', ['-u', '--color=always', backupPath, enrichedPath], {
          encoding: 'utf-8',
          stdio: ['pipe', 'pipe', 'pipe'],
        });
        console.log(diff || '  (no changes)');
      } catch (err: any) {
        // diff exits 1 when files differ — that's the normal case
        if (err.stdout) {
          console.log(err.stdout);
        }
      }
      console.log('');
    }

    console.log(`Backups saved to ${backupDir}`);
  }

  return result;
}
