/**
 * Manifest tracks which files were generated by fixedcode, enabling safe regeneration.
 * Generated files are overwritten. Extension points (overwrite: false) are generated once.
 * User files not in the manifest are never touched.
 */
import { createHash } from 'node:crypto';
import { resolve, relative } from 'node:path';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const MANIFEST_FILE = '.fixedcode-manifest.json';

export interface ManifestEntry {
  hash: string;
  bundle: string;
  overwrite: boolean;
  /** Path to the spec that generated this file (relative to outputDir) */
  specFile?: string;
}

export interface Manifest {
  generatedAt: string;
  engine: string;
  bundles: Record<string, string>;
  files: Record<string, ManifestEntry>;
}

export function readManifest(outputDir: string): Manifest | null {
  const path = resolve(outputDir, MANIFEST_FILE);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    return null;
  }
}

export function writeManifest(outputDir: string, manifest: Manifest): void {
  const path = resolve(outputDir, MANIFEST_FILE);
  mkdirSync(outputDir, { recursive: true });
  writeFileSync(path, JSON.stringify(manifest, null, 2) + '\n', 'utf-8');
}

export function hashContent(content: string): string {
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}

/**
 * Determine whether a file should be written based on manifest and overwrite flag.
 * Returns: 'write' | 'skip' | 'warn-overwrite'
 */
export function shouldWrite(
  relPath: string,
  overwrite: boolean,
  outputDir: string,
  manifest: Manifest | null
): 'write' | 'skip' | 'warn-overwrite' {
  const absPath = resolve(outputDir, relPath);

  if (!existsSync(absPath)) {
    // File doesn't exist yet — always write
    return 'write';
  }

  if (!overwrite) {
    // Extension point — file exists, don't touch it
    return 'skip';
  }

  // File exists and overwrite is true
  if (manifest) {
    const entry = manifest.files[relPath];
    if (entry) {
      // We generated this before — safe to overwrite
      return 'write';
    }
    // File exists but wasn't in our manifest — user-created file at a generated path
    return 'warn-overwrite';
  }

  // No manifest (first run or manifest deleted) — overwrite
  return 'write';
}

/**
 * Check if a path matches any pattern in .fixedcodeignore.
 * Patterns are simple glob-like: *.kt, src/main/**, Default*.kt, etc.
 */
export function loadIgnorePatterns(projectDir: string): string[] {
  const ignorePath = resolve(projectDir, '.fixedcodeignore');
  if (!existsSync(ignorePath)) return [];
  return readFileSync(ignorePath, 'utf-8')
    .split('\n')
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('#'));
}

export function isIgnored(relPath: string, patterns: string[]): boolean {
  for (const pattern of patterns) {
    if (matchGlob(relPath, pattern)) return true;
  }
  return false;
}

/**
 * Simple glob matcher. Supports `*` (single segment) and `**` (any depth).
 * Limitation: does not support `?`, character classes `[abc]`, or negation `!`.
 */
function matchGlob(path: string, pattern: string): boolean {
  const regex = pattern
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')  // escape all regex specials except * and ?
    .replace(/\*\*/g, '{{DOUBLESTAR}}')
    .replace(/\*/g, '[^/]*')
    .replace(/\{\{DOUBLESTAR\}\}/g, '.*');
  return new RegExp(`^${regex}$`).test(path);
}
