---
name: PIDP CI MCP Wrapper
run-name: ${{ "{{" }} github.workflow {{ "}}" }}

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: PEXA-AU/pidp-workflows/.github/workflows/build-python.yaml@v5
    secrets: inherit
    with:
      push-image: true
