/**
 * Test the full engine pipeline with generators.
 * This uses the engine's generate() function which will:
 * 1. Parse spec → 2. Resolve bundle → 3. Enrich → 4. Render templates → 5. Run generators
 */
import { generate } from '../../engine/src/engine/pipeline.js';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputDir = resolve(__dirname, 'build-pipeline');

async function main() {
  console.log('=== Running spring-domain through engine pipeline ===\n');

  await generate(
    resolve(__dirname, 'workspace-domain.yaml'),
    { outputDir }
  );

  console.log(`\nOutput written to: ${outputDir}`);

  // Check if the OpenAPI spec was generated by the generator
  const { existsSync, readdirSync } = await import('node:fs');
  const files = readdirSync(outputDir);
  const openapiFile = files.find(f => f.includes('openapi'));
  if (openapiFile) {
    console.log(`\nOpenAPI spec generated: ${openapiFile}`);
  } else {
    console.log('\nOpenAPI spec NOT found — generator may not have run');
    console.log('Files in output root:', files.join(', '));
  }
}

main().catch(err => { console.error(err); process.exit(1); });
